#!/usr/bin/python3
from sys import argv

def division(n):
    """perform trial division to find prime factors of a number.

    Args:
        n (int): The number to be factorized.

    Returns:
        list: A list of prime factors of the input number.
    """
    factors = []

    while n % 2 == 0:
        factors.append(2)
        n //= 2

    for i in range(3, int(n**0.5) + 1, 2):
        while n % i == 0:
            factors.append(i)
            n //= i

    if n > 2:
        factors.append(n)

    return factors

def prime_factorization(number):
    """compute prime factorization of a number.
    Args:
        number (int): number to be factorized.
    Returns:
        str: string representing the prime factorization of the input number.
    """
    factors = division(number)
    return '*'.join(map(str, factors))

if len(argv) != 2:
    print("Usage: python script.py input_file.txt")
    exit(1)

with open(argv[1]) as file:
    """factorize numbers from a file and print the results.
    Args:
        file_path (str): The path to file containing natural numbers to factor.
    """
    for line in file:
        number = int(line)
        print("{:d}=".format(number), end="")
        if number % 2 == 0:
            print("{}*2".format(number // 2))
        else:
            result = prime_factorization(number)
            print(result)

